### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by milankl** [milankl/StochasticRounding.jl#60]
@avleenk2312 suggests to add complex number support. This is without any additional code generally supported as `Float16sr`, `BFloat16sr` and `Float32sr` are all `<:AbstractFloat`
```julia
julia> b = Complex{Float16sr}.(rand(4))
4-element Vector{Complex{Float16sr}}:
  Float16sr(0.5683594) + Float16sr(0.0)im
 Float16sr(0.25219727) + Float16sr(0.0)im
 Float16sr(0.07757568) + Float16sr(0.0)im
 Float16sr(0.07165527) + Float16sr(0.0)im

julia> A = Complex{Float16sr}.(rand(ComplexF64,4,4))
4×4 Matrix{Complex{Float16sr}}:
 Float16sr(0.16442871)+Float16sr(0.027038574)im  …    Float16sr(0.8027344)+Float16sr(0.9423828)im
 Float16sr(0.64501953)+Float16sr(0.3605957)im        Float16sr(0.40014648)+Float16sr(0.8051758)im
  Float16sr(0.7607422)+Float16sr(0.5761719)im       Float16sr(0.027954102)+Float16sr(0.25805664)im
  Float16sr(0.7861328)+Float16sr(0.13891602)im        Float16sr(0.6381836)+Float16sr(0.44384766)im

julia> A\b
4-element Vector{Complex{Float16sr}}:
  Float16sr(-1.2207031) + Float16sr(0.8798828)im
   Float16sr(0.1508789) - Float16sr(0.71191406)im
   Float16sr(0.8178711) - Float16sr(0.77197266)im
 Float16sr(-0.19714355) + Float16sr(0.38745117)im
```
However, for packages like `GenericFFT`, additional functionality may be required. @avleenk2312 could you post your errors here?

**Comment by avleenk2312** [comment]
Thanks a lot for your suggestions.
The code that I am working on has several modules, so it took me some time to go over it and adjust the code as you suggested. First, I forgot to use `Complex{Float32sr}`, so that fixed some errors. Secondly, the code uses `rfft` and `irfft` functions from the [FFTW](https://github.com/JuliaMath/FFTW.jl) package in some modules, which doesn't support `Float32sr`.  For instance, see the following screenshots which show a toy example of the actual code. Here, `phi` is of type `Array{Float32sr,1}`. In order to get the code running, I cast `phi` to `Float32` and then cast the outback back to `Complex{Float32sr}`. 

<img width="1685" alt="Screenshot 2022-12-07 at 12 17 55 PM" src="https://user-images.githubusercontent.com/87992106/206266812-6580ef7d-84f4-44ac-ac6e-3e30cc54e202.png">
<img width="540" alt="Screenshot 2022-12-07 at 12 18 10 PM" src="https://user-images.githubusercontent.com/87992106/206266818-dc6ac2e3-234c-418b-a8e1-a76c7f29b908.png">
<img width="649" alt="Screenshot 2022-12-07 at 12 18 18 PM" src="https://user-images.githubusercontent.com/87992106/206266821-625bacb6-d5b0-4d89-97f9-fe6dc41a9b8e.png">

As you said that additional functionality may be required for packages like GenericFFT, do you have any ideas on getting [FFTW](https://github.com/JuliaMath/FFTW.jl) to work with `Float32sr.` I will be happy to take a look at that as well. Thanks.

**Comment by milankl** [comment]
(For the future, just copy in your code within a ` ```julia` ... ` ``` ` block)

FFTW only supports Float32/64 and there's no easy way to extend it. This is because it's written in C/OCaml, so when you call something from FFTW you actually leave Julia land. That's why people started writing GenericFFT and it's on my todo list to improve it, but it currently doesn't have a high priority unfortunately...

So at the moment I would do as you suggest, reinterpret (there is no casting/converting needed as it's the same bits!) to Float32 and then do the fft without stochastic rounding and then get back into Float32sr afterwards.

**Comment by avleenk2312** [comment]
Thanks for your quick response and suggestions. Sorry, I had been casting things from double to single precision so it just stayed stuck in my head. Okay, I will keep doing the same process for using FFTW.
