### ISSUE TITLE
`Float16_chance_roundup` direct from a Float64?

### ISSUE THREAD

**Issue by cbm755** [milankl/StochasticRounding.jl#63]
Great tool, looking forward to playing with it!

This works:
```julia
julia> Float32_chance_roundup(1.0/3)
0.666666666045785
```

But this does not:
```julia
julia> Float16_chance_roundup(1.0/3)
ERROR: MethodError: no method matching Float16_chance_roundup(::Float64)

Closest candidates are:
  Float16_chance_roundup(::Float32)
   @ StochasticRounding ~/.julia/packages/StochasticRounding/oFmFq/src/float16sr.jl:73

Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

Of course, I can:
```julia
julia> Float16_chance_roundup(Float32(1.0/3))
0.33337402f0
```

Is there a reason to disallow `::Float64`?

**Comment by milankl** [comment]
Sorry, only saw this now. Good point. I'd probably just define
```julia
Float16_chance_roundup(x::Real) = Float16_chance_roundup(Float32(x))
```
because as you correctly realised, it's not about the type you throw in. Looking at the `Float??_chance_roundup` functions, I believe one could also write them as parametric functions with directly with `x::T` and then avoid the extra method above, but maybe that's also just an overkill

**Comment by milankl** [comment]
Realised that this only makes sense for `Float16_chance_roundup(x::Float64)`, i.e. precision two formats higher than where we'd want to round to. Similar for `BFloat16_chance_roundup(x::Float64)`, but actually all the other ones are either already implemented or just zero

```julia
Float16_chance_roundup(x::Float16) = 0
Float32_chance_roundup(x::Float16) = 0
Float32_chance_roundup(x::Float32) = 0
Float64_chance_roundup(x::Float16) = 0
Float64_chance_roundup(x::Float32) = 0
Float64_chance_roundup(x::Float64) = 0
```
because lower precision float formats are always contained within the higher ones.

**Comment by milankl** [comment]
#73 wil address this
